[package]
name = "fst-native"
version = "0.8.4"
edition = "2021"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "FST wavedump format reader implemented in safe Rust."
repository = "https://github.com/ekiwi/fst-native"
license = "BSD-3-Clause"
include = ["Cargo.toml", "LICENSE", "src/"]
keywords = ["fst", "waveform", "wavedump"]

[dependencies]
lz4_flex = "0.11.1"
flate2 = "1.0"
num_enum = "0.7.0"
tempfile = "3"
thiserror = "1.0.58"

[dev-dependencies]
clap = { version = "4.4.6", features = ["derive"] }
fst-sys = "0.2.0"
leb128 = "0.2.5"
proptest = "1.3.1"
proptest-derive = "0.4.0"
vcd = "0.7.0"

